import {Metadata} from "next";
import React, {Suspense} from 'react'
import {Refine, GitHubBanner,} from '@refinedev/core';
import {DevtoolsProvider} from '@providers/devtools'
import {RefineKbar, RefineKbarProvider} from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";


import {Layout} from "@components/layout";
import "@styles/global.css";
import './global.css';

import {authProvider} from "@providers/auth-provider";
import {dataProvider} from "@providers/data-provider";


export const metadata: Metadata = {
    title: "Refine",
    description: "Generated by create refine app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
                  rel="stylesheet"/>
        </head>
        <body>
        <Suspense>
            <RefineKbarProvider>

                <DevtoolsProvider>
                    <Refine
                        routerProvider={routerProvider}
                        authProvider={authProvider}
                        dataProvider={dataProvider}
                        resources={[
                            {
                                name: "blog-posts",
                                list: "/blog-posts",
                                create: "/blog-posts/create",
                                edit: "/blog-posts/edit/:id",
                                show: "/blog-posts/show/:id",
                                meta: {
                                    canDelete: true,
                                },
                            },
                            {
                                name: "categories",
                                list: "/categories",
                                create: "/categories/create",
                                edit: "/categories/edit/:id",
                                show: "/categories/show/:id",
                                meta: {
                                    canDelete: true,
                                },
                            }
                        ]}
                        options={{
                            syncWithLocation: true,
                            warnWhenUnsavedChanges: true,
                            useNewQueryKeys: true,
                            projectId: "bgrGUU-GmnbnG-ObGU0e",

                        }}
                    >
                        {children}
                        <RefineKbar/>
                    </Refine>
                </DevtoolsProvider>

            </RefineKbarProvider>
        </Suspense>
        </body>
        </html>
    );
}
