name: Release to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish the web
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Prepare the distro
        run: ./build.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PROD_AWS_REGION }}

      - name: Deploy
        run: aws s3 sync ./public s3://bonitoo.io --cache-control max-age=60 --delete

      - name: Invalidate CF Distribution
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.PROD_CF_DISTRIBUTION_ID }} --paths '/*'